# Bases de datos en Python

Es clave saber conectarse a bases de datos desde diferentes softwares. Sin embargo, la mayoría de las veces vamos a requerir procesar los datos de la base y para eso requerimos traer los datos a Python.

Vamos a hacer la misma conexión que hicimos con DBeaver pero ahora directamente en Python

In [14]:
from sqlalchemy import create_engine, text #Tambien requerimos **pip install pymysql
import pandas as pd

Levantamos la conexión al paserle los valores de configuración de la base de datos

In [16]:
db_config = {
        
            "username" : "anonymous",
            "password" : "",
            "host" : "ensembldb.ensembl.org",
            "port" : "3306",
            "db" : "homo_sapiens_core_109_38",
            "table" : "gene",
}

In [18]:
# Formato de la cadena de conexión:
# 'mysql+pymysql://usuario:contraseña@host:puerto/nombre_base_datos'

engine = create_engine(f'mysql+pymysql://{db_config["username"]}:{db_config["password"]}@{db_config["host"]}:{db_config["port"]}/{db_config["db"]}')

In [20]:
# Hagámos un querry ara bajar TODA la información de la tabla

query = text(f"SELECT * FROM {db_config["table"]}")

In [22]:
# Corremos el query y lo guardamos en una variable con pandas

data = pd.read_sql(query, engine)

In [24]:
data

,gene_id,biotype,analysis_id,seq_region_id,seq_region_start,seq_region_end,seq_region_strand,display_xref_id,source,description,is_current,canonical_transcript_id,stable_id,version,created_date,modified_date
0,554,Mt_tRNA,1,132907,577,647,1,2898423.0,insdc,mitochondrially encoded tRNA-Phe (UUU/C) [Sour...,1,1587,ENSG00000210049,1,2006-05-12 00:00:00,2006-05-12 00:00:00
1,555,Mt_rRNA,1,132907,648,1601,1,2898394.0,insdc,mitochondrially encoded 12S rRNA [Source:HGNC ...,1,1588,ENSG00000211459,2,2006-07-03 00:00:00,2010-01-08 18:00:56
2,556,Mt_tRNA,1,132907,1602,1670,1,2898486.0,insdc,mitochondrially encoded tRNA-Val (GUN) [Source...,1,1589,ENSG00000210077,1,2006-05-12 00:00:00,2006-05-12 00:00:00
3,557,Mt_rRNA,1,132907,1671,3229,1,2898399.0,insdc,mitochondrially encoded 16S rRNA [Source:HGNC ...,1,1590,ENSG00000210082,2,2006-05-12 00:00:00,2010-01-08 18:00:56
4,558,Mt_tRNA,1,132907,3230,3304,1,2898448.0,insdc,mitochondrially encoded tRNA-Leu (UUA/G) 1 [So...,1,1591,ENSG00000209082,1,2006-05-12 00:00:00,2006-05-12 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70618,139191,protein_coding,8353,131550,64745075,64833232,1,2934580.0,ensembl_havana,"ribonucleoprotein, PTB binding 2 [Source:HGNC ...",1,546099,ENSG00000162437,15,2008-04-29 11:17:41,2021-09-14 13:12:43
70619,139192,protein_coding,8353,131550,84506300,84567379,1,2972751.0,ensembl_havana,spermatogenesis associated 1 [Source:HGNC Symb...,1,546106,ENSG00000122432,19,2008-04-29 11:17:41,2022-01-12 10:16:27
70620,139193,lncRNA,8354,131550,84574114,84583620,1,NaN,havana,novel transcript,1,546112,ENSG00000284882,2,2018-01-17 17:12:04,2022-01-12 10:16:27
70621,139194,lncRNA,9923,131550,84614068,84621061,-1,NaN,havana_tagene,novel transcript,1,546115,ENSG00000289881,1,2022-01-12 10:16:27,2022-01-12 10:16:27
70622,139195,lncRNA,8354,131550,84785427,84786714,1,NaN,havana,novel transcript,1,546116,ENSG00000285325,1,2018-01-17 17:12:04,2018-01-17 17:12:04

In [30]:
data.columns

Index(['gene_id', 'biotype', 'analysis_id', 'seq_region_id',
       'seq_region_start', 'seq_region_end', 'seq_region_strand',
       'display_xref_id', 'source', 'description', 'is_current',
       'canonical_transcript_id', 'stable_id', 'version', 'created_date',
       'modified_date'],
      dtype='object')